-- 创建每日代办表
CREATE TABLE IF NOT EXISTS todo (
  id INT UNSIGNED AUTO_INCREMENT COMMENT '待办ID',
  title VARCHAR(100) NOT NULL COMMENT '待办标题',
  content TEXT COMMENT '待办内容',
  status TINYINT UNSIGNED DEFAULT 0 COMMENT '完成状态（0:未完成 1:已完成）',
  progress TINYINT UNSIGNED DEFAULT 0 COMMENT '完整进度（0-100）'
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='每日代办表';