CREATE TABLE IF NOT EXISTS blog_image (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  blog_id INT UNSIGNED NOT NULL COMMENT '关联博客ID',
  image_path VARCHAR(255) NOT NULL COMMENT '服务器图片存储路径',
  image_type VARCHAR(50) COMMENT '图像类型（如jpg/png）',
  is_cover TINYINT(1) DEFAULT 0 COMMENT '是否为封面图（0-否，1-是）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  FOREIGN KEY (blog_id) REFERENCES blog(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='博客图片表';